---
title: "Final Report"
output: 
  html_document:
    toc: true
    toc_float: true
    code_folding: hide 
   
---


## Motivation  

The motivation behind this project comes from the consistent political discourse around abortion laws. Abortion laws in the United States has a long history of being politicized, often being brought up as a leading point in Women's Rights advocacy. When Roe v Wade, one of the most important and groundbreaking pieces of legislation to ever be enacted regarding abortion, was overturned in June 2022 this created an uproar. We started to see abortion facilities decreasing in Red states and stricter laws being enforced. With both midterm elections and the new major threat to reproductive rights happening in 2022, our group found this to be a timely and pressing public health issue to address. 

## Initial Questions 

Based on the available data we were interested in answering the following questions: 

- How has voter turnout changed by state between 2018 and 2022? 
- Since the overturn of Roe v Wade how has accessibility to abortion clinics changed between June 2022 and July 2022? 
- How do abortion laws and restrictions differ among each state? 

## Data Processing and Cleaning

*Cleaning Each Data Set* 

1. Abortion Clinic Distances By County and State [dataset](https://osf.io/pfxq3/)

2. Abortion Laws By State [dataset](https://lawatlas.org/datasets/abortion-bans)

3. Voter Turnout By State [dataset](https://www.electproject.org/2022g)

*Merging the Data Sets* 


## Exploratory Analysis 


## Discussion

